# Generated by Django 5.1.4 on 2024-12-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('balance', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User Data',
                'verbose_name_plural': 'Users Data',
            },
        ),
    ]
