# Generated by Django 5.1.4 on 2024-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transitions_code', models.IntegerField(unique=True)),
                ('amount', models.IntegerField()),
                ('data_time', models.DateTimeField(auto_now=True, null=True)),
                ('is_payed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-data_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='amount_positive')],
            },
        ),
    ]
