# Generated by Django 5.1.4 on 2024-12-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transitions_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('amount', models.IntegerField()),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=686588127, on_delete=django.db.models.deletion.CASCADE, to='users.userdata', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transition',
                'verbose_name_plural': 'Transitions',
                'ordering': ['-paid_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='amount_positive')],
            },
        ),
    ]
