# Generated by Django 5.1.4 on 2024-12-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transitions_transitions_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitions',
            name='data_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
