# Generated by Django 5.1.4 on 2024-12-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transitions_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitions',
            name='transitions_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
