# Generated by Django 5.1.4 on 2024-12-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_transitions_transitions_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transitions',
            options={'ordering': ['-data_time'], 'verbose_name': 'Transition', 'verbose_name_plural': 'Transitions'},
        ),
    ]
